name: DependaBot Update Check via Ruby

on:
  pull_request:
    paths:
      - Gemfile
      - Gemfile.lock

jobs:

  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@master
      with:
        ruby-version: 2.6.x
    - name: Bundle and Update
      run: |
        gem install bundler
        bundle config set no-cache 'true'
        bundle config set path 'vendor/bundle'
        bundle install --jobs 12 --retry 3
        # bundle update --all --jobs 12

  merge:

    needs:
      - check

    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
